application_port: 8000
database:
  database_name: "newsletter"
  host: "127.0.0.1"
  password: "password"
  port: 5432
  username: "postgres"
email_client:
  base_url: "https://api.postmarkapp.com"
  sender_email: "jean-christophe.maigrot@zenika.com"
  authorization_token: "my-secret-token"
